### ISSUE TITLE
Using BidPrice for Spot Instances overstates cluster cost

### ISSUE THREAD

**Issue by gstaubli** [memosstilvi/emr-cost-calculator#3]
https://github.com/memosstilvi/emr-cost-calculator/blob/master/emr_cost_calculator.py#L190

Using the BidPrice means the value of the cluster is reported as being the maximum bid price specified by the user times the lifetime in hours of those instances (https://github.com/memosstilvi/emr-cost-calculator/blob/master/emr_cost_calculator.py#L64)

This is incorrect because the actual cost of the instance per hour is determined by the Spot Instance Market, which fluctuates (in this case) between points of the spot instances price floor and the user's max bid price. A four instance EMR cluster that runs for 10 hours at a bid price of $0.37/hour would be returned by this calculator as having cost $14.8 ($0.37 \* 4 \* 10). However in actuality the cost would have been ($0.20 \* 4 \* 8) + ($0.37 \* 4 \* 2) = $9.36 (~36.8% cost difference) because the actual cost per instance was only $0.20/hour for 8 hours and the max bid price of $0.37/hour for 2 hours. Also, EMR nodes have an added fixed EMR node fee per hour (in addition to the EC2 instance cost, whether on demand or spot).

**Comment by gstaubli** [comment]
In fairness, this issue is alluded to in the readme, although the EMR fixed fee per node hour is still an outstanding issue.

**Comment by memosstilvi** [comment]
Thank you for this issue @gstaubli. I pushed a commit that adds the EMR fixed fee to the instance hourly price.

As for the difference between BidPrice and ActualPrice I believe that is a good enough approximation for now.
However, I would gladly merge a PR that fixes this discrepancy as well :)

I consider this issue closed, since the BidPrice vs ActualPrice discrepancy is already mentioned in the README.
